import type { ControlDTO } from '@dtos';

const getRandomDate = () => {
  const start = new Date(2022, 0, 1);
  const end = new Date();
  return new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime()),
  ).toISOString();
};

const users = ['admin', 'john.doe', 'jane.smith', 'bob.wilson', 'alice.cooper'];
const getRandomUser = () => users[Math.floor(Math.random() * users.length)];

export const MOCK_CONTROL = [
  {
    createdDate: getRandomDate(),
    createdBy: getRandomUser(),
    updatedDate: getRandomDate(),
    updatedBy: getRandomUser(),
    id: '1',
    code: 'C01',
    name: 'Control 1',
    status: 'ACTIVE',
    controlType: 'TEXT',
  },
  {
    createdDate: getRandomDate(),
    createdBy: getRandomUser(),
    updatedDate: getRandomDate(),
    updatedBy: getRandomUser(),
    id: '2',
    code: 'C02',
    name: 'Control 2',
    status: 'ACTIVE',
    controlType: 'SELECT',
  },
  {
    createdDate: getRandomDate(),
    createdBy: getRandomUser(),
    updatedDate: getRandomDate(),
    updatedBy: getRandomUser(),
    id: '3',
    code: 'C03',
    name: 'Control 3',
    status: 'ACTIVE',
    controlType: 'RADIO',
  },
  {
    createdDate: getRandomDate(),
    createdBy: getRandomUser(),
    updatedDate: getRandomDate(),
    updatedBy: getRandomUser(),
    id: '4',
    code: 'C04',
    name: 'Control 4',
    status: 'ACTIVE',
    controlType: 'CHECKBOX',
  },
  {
    createdDate: getRandomDate(),
    createdBy: getRandomUser(),
    updatedDate: getRandomDate(),
    updatedBy: getRandomUser(),
    id: '5',
    code: 'C05',
    name: 'Control 5',
    status: 'ACTIVE',
    controlType: 'IMAGE',
  },
  {
    createdDate: getRandomDate(),
    createdBy: getRandomUser(),
    updatedDate: getRandomDate(),
    updatedBy: getRandomUser(),
    id: '6',
    code: 'C06',
    name: 'Control 6',
    status: 'ACTIVE',
    controlType: 'DATETIME',
  },
  {
    createdDate: getRandomDate(),
    createdBy: getRandomUser(),
    updatedDate: getRandomDate(),
    updatedBy: getRandomUser(),
    id: '7',
    code: 'C07',
    name: 'Control 7',
    status: 'ACTIVE',
    controlType: 'NUMBER',
  },
  {
    createdDate: getRandomDate(),
    createdBy: getRandomUser(),
    updatedDate: getRandomDate(),
    updatedBy: getRandomUser(),
    id: '8',
    code: 'C08',
    name: 'Control 8',
    status: 'ACTIVE',
    controlType: 'SWITCH',
  },
  {
    createdDate: getRandomDate(),
    createdBy: getRandomUser(),
    updatedDate: getRandomDate(),
    updatedBy: getRandomUser(),
    id: '9',
    code: 'C09',
    name: 'Control 9',
    status: 'ACTIVE',
    controlType: 'LINK',
  },
  {
    createdDate: getRandomDate(),
    createdBy: getRandomUser(),
    updatedDate: getRandomDate(),
    updatedBy: getRandomUser(),
    id: '10',
    code: 'C10',
    name: 'Control 10',
    status: 'ACTIVE',
    controlType: 'EDITOR',
  },
] as ControlDTO[];
