export const DATE_SLASH_FORMAT = 'YYYY/MM/DD';

export const DATE_SLASH_FORMAT_DDMMYYYY = 'DD/MM/YYYY';

export const DATE_HYPHEN_FORMAT_YYYYMMDD = 'YYYY-MM-DD';

export const DATE_SLASH_FORMAT_DDMMYYYY_HHMMSS = 'DD/MM/YYYY HH:mm:ss';
