// src/utils/axiosInstance.js
import { BASE_URL } from '@constants/baseUrl';
import axios from 'axios';

const axiosInstance = axios.create({
  baseURL: BASE_URL,
  headers: {
    'Content-Type': 'application/json',
    Authorization:
      'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJZT1VIU0xUblZsc0tKT3BDVHk1b2J4ZGRycUdiZ1EtOVNMd2RfVE85M0JzIn0.eyJleHAiOjE3Mzg3NTQwMzEsImlhdCI6MTczODc1MzczMSwianRpIjoiNDhhZjdiY2UtMDAzZC00Njc3LTgwNGUtMzNiM2MzMGQ2YWYyIiwiaXNzIjoiaHR0cDovL2Ntc3NvLmFwc3Byby5zaXRlL3JlYWxtcy9tYi1jbSIsInN1YiI6IjQwOWVhZjcwLTkyMmYtNGRkZS04YWE4LWVkOGY5NGI5ZmUyYyIsInR5cCI6IkJlYXJlciIsImF6cCI6Im1iLWNtLXNlcnZpY2UiLCJzaWQiOiJiZjE1YTlkMi0xNDU0LTRkMjktOTNhZi04NzFlYmUyYTM3N2MiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIi8qIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiYWRtaW4gaGloaSIsInByZWZlcnJlZF91c2VybmFtZSI6Im1iY20iLCJnaXZlbl9uYW1lIjoiYWRtaW4iLCJmYW1pbHlfbmFtZSI6ImhpaGkiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSJ9.tz0gQCTR2FxW1NEpvXoW_rIpIl_i1tSj0-QBYobU5Z7iSbig-D_9xNwQLUVwo114cQfZtXcMs0ATJCS-3oP_tcwo9WeIY8nj1B43ff1XbmtDC3izriBg88LOFYeuCRBcqFn8KYKAufRJXCAe3_kUnK9qFL3XqH_s3MTmyI71DnF1uJ0IEFfOhsjvmRjG2bbxOosvLfccFWpzu-FyMNc7zhmMGGngvEIcaRPRZYhRVPNAHXQoFShv_8_Hw53TQlfmdNiz1d-qKsdvPBo8eRAfGV0Mw_AkOmf4l-eUc_bIyq4vGBPnnggTA6cu9SAO9F-_w5G_U0DttHEfqg-TbkugEA',
  },
});

export default axiosInstance;
